2018-09-17T01:20:12.0536760+04:00 0HLGS38AM2DSN:0000002F [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:20:13.8724880+04:00 0HLGS38AM2DSN:0000002F [ERR] da64a328-c34e-492d-b9fd-f160c0678bdb (4a22d6e4)
2018-09-17T01:20:13.8839760+04:00 0HLGS38AM2DSN:0000002F [ERR] http localhost:5000 /api/phase/14/workCategory   (fee79034)
2018-09-17T01:20:13.8899940+04:00 0HLGS38AM2DSN:0000002F [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: da64a328-c34e-492d-b9fd-f160c0678bdb გაუგზავნეთ ადმინისტრატორს","data":false} (4552d8cf)
2018-09-17T01:20:13.9566970+04:00 0HLGS38AM2DSN:0000002F [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (6105024d)
2018-09-17T01:22:05.7801130+04:00 0HLGS39CQ8TC2:0000000F [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:22:07.5772170+04:00 0HLGS39CQ8TC2:0000000F [ERR] cfc2de0c-e8e9-451e-99cf-270ffdfecdd6 (dfb2f4bf)
2018-09-17T01:22:07.6015940+04:00 0HLGS39CQ8TC2:0000000F [ERR] http localhost:5000 /api/phase/14/workCategory   (fee79034)
2018-09-17T01:22:07.6089540+04:00 0HLGS39CQ8TC2:0000000F [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: cfc2de0c-e8e9-451e-99cf-270ffdfecdd6 გაუგზავნეთ ადმინისტრატორს","data":false} (7a48e84d)
2018-09-17T01:22:07.6841000+04:00 0HLGS39CQ8TC2:0000000F [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (6105024d)
2018-09-17T01:25:19.0756900+04:00 0HLGS3B2DSGJV:0000001A [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:25:20.9636260+04:00 0HLGS3B2DSGJV:0000001A [ERR] 68bf5883-6be5-496b-a111-95e4c55f1cca (090cb68f)
2018-09-17T01:25:20.9773490+04:00 0HLGS3B2DSGJV:0000001A [ERR] http localhost:5000 /api/phase/14/workCategory   (fee79034)
2018-09-17T01:25:20.9840770+04:00 0HLGS3B2DSGJV:0000001A [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: 68bf5883-6be5-496b-a111-95e4c55f1cca გაუგზავნეთ ადმინისტრატორს","data":false} (8eb0c285)
2018-09-17T01:25:21.0479260+04:00 0HLGS3B2DSGJV:0000001A [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (6105024d)
2018-09-17T01:33:50.2461050+04:00 0HLGS3FJGTC9J:00000013 [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:33:52.6521830+04:00 0HLGS3FJGTC9J:00000013 [ERR] 656261ca-642b-495b-96b3-361c6c17cef8 (9cb44db5)
2018-09-17T01:33:52.6969880+04:00 0HLGS3FJGTC9J:00000013 [ERR] http localhost:5000 /api/phase/14/workCategory   (fee79034)
2018-09-17T01:33:52.7048110+04:00 0HLGS3FJGTC9J:00000013 [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: 656261ca-642b-495b-96b3-361c6c17cef8 გაუგზავნეთ ადმინისტრატორს","data":false} (69c41538)
2018-09-17T01:33:52.7757810+04:00 0HLGS3FJGTC9J:00000013 [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.HasRoles(String token, Int32[] roles) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 79
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (6105024d)
2018-09-17T01:35:30.9623370+04:00 0HLGS3H3J5F61:0000000C [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:35:32.8343800+04:00 0HLGS3H3J5F61:0000000C [ERR] 35eda227-0f7a-4849-952c-4dc255c44b0c (0151eb6a)
2018-09-17T01:35:32.8595750+04:00 0HLGS3H3J5F61:0000000C [ERR] http localhost:5000 /api/phase/13/workCategory   (15d48844)
2018-09-17T01:35:32.8669220+04:00 0HLGS3H3J5F61:0000000C [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: 35eda227-0f7a-4849-952c-4dc255c44b0c გაუგზავნეთ ადმინისტრატორს","data":false} (6c0714c1)
2018-09-17T01:35:32.9287230+04:00 0HLGS3H3J5F61:0000000C [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (44be49df)
2018-09-17T01:40:04.2200660+04:00 0HLGS3JM2D5UG:0000000D [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:40:06.0039010+04:00 0HLGS3JM2D5UG:0000000D [ERR] b79331ee-7850-4903-a94d-ef2355e0c7fd (b9aecead)
2018-09-17T01:40:06.0276590+04:00 0HLGS3JM2D5UG:0000000D [ERR] http localhost:5000 /api/phase/14/workCategory   (fee79034)
2018-09-17T01:40:06.0339110+04:00 0HLGS3JM2D5UG:0000000D [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: b79331ee-7850-4903-a94d-ef2355e0c7fd გაუგზავნეთ ადმინისტრატორს","data":false} (f44ba94e)
2018-09-17T01:40:06.0951860+04:00 0HLGS3JM2D5UG:0000000D [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (44be49df)
2018-09-17T01:42:01.5329600+04:00 0HLGS3KHES957:0000005E [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31
2018-09-17T01:42:03.2801970+04:00 0HLGS3KHES957:0000005E [ERR] 956f2dcb-50c3-4a44-8ba2-9a6982dfe1a7 (30c71026)
2018-09-17T01:42:03.3098590+04:00 0HLGS3KHES957:0000005E [ERR] http localhost:5000 /api/phase/13/workCategory   (15d48844)
2018-09-17T01:42:03.3217640+04:00 0HLGS3KHES957:0000005E [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: 956f2dcb-50c3-4a44-8ba2-9a6982dfe1a7 გაუგზავნეთ ადმინისტრატორს","data":false} (9a0e4e82)
2018-09-17T01:42:03.4012660+04:00 0HLGS3KHES957:0000005E [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (44be49df)
2018-09-17T01:52:34.1841100+04:00 0HLGS3KHES95E:0000000F [ERR] An exception occurred in the database while iterating the results of a query for context type '"Cs.Persistence.CsDbContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)" (64e2593c)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
2018-09-17T01:52:36.1219780+04:00 0HLGS3KHES95E:0000000F [ERR] eeccb84d-90fb-4964-8813-3ed76e7c0f49 (26a94511)
2018-09-17T01:52:36.1464310+04:00 0HLGS3KHES95E:0000000F [ERR] http localhost:5000 /api/workCategory/6/work   (fac80c96)
2018-09-17T01:52:36.1558100+04:00 0HLGS3KHES95E:0000000F [ERR] Response: {"success":false,"errorOccured":true,"message":"დაფიქსირდა შეცდომა, შეცდომის კოდი: eeccb84d-90fb-4964-8813-3ed76e7c0f49 გაუგზავნეთ ადმინისტრატორს","data":false} (8baa7b98)
2018-09-17T01:52:36.1662900+04:00 0HLGS3KHES95E:0000000F [ERR] System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Cs.Application.Auth.AuthService.IsTokenValid(String token) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Application/Auth/AuthService.cs:line 67
   at Cs.Service.Configuration.Filters.AuthFilter.OnAuthorization(AuthorizationFilterContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Filters/AuthFilter.cs:line 40
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cs.Service.Configuration.Middlewares.LogAndExceptionHandler.Invoke(HttpContext context) in /Users/needermen/Code/ConstructionSoft/trunk/ConstructionSoft/Backend/Source/Cs.Service/Configuration/Middlewares/LogAndExceptionHandler.cs:line 31 (44be49df)
